<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class RetsPropertyDataPurged extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        //
        Schema::create('RetsPropertyDataPurged', function (Blueprint $table) {
            $table->bigIncrements('id',);
            $table->integer('mls_no')->default('1');
            $table->string('InternalID',50)->nullable();
            $table->string('ABA',30)->default('No');
            $table->integer('ApplicationFee')->nullable();
            $table->integer('BathroomsFull')->nullable();
            $table->integer('BathroomsHalf')->nullable();
            $table->integer('BathroomsTotalInteger')->nullable();
            $table->integer('BedroomsTotal')->nullable();
            $table->text('LandingPageUrl');
            $table->text('Headline');
            $table->string('MlsStatus',50)->nullable()->default('NULL');
            $table->string('ListingId',30)->default('');
            $table->string('StreetNumber',25)->nullable()->default('NULL');
            $table->string('StreetDirPrefix',50)->nullable()->default('NULL');
            $table->string('StreetName',50)->nullable()->default('NULL');
            $table->string('StreetSuffix',150);
            $table->string('UnitNumber',25)->nullable()->default('NULL');
            $table->string('StreetDirSuffix',50)->nullable()->default('NULL');
            $table->string('City',50)->nullable()->default('NULL');
            $table->string('StateOrProvince',50)->nullable()->default('NULL');
            $table->string('PostalCode',10)->nullable()->default('NULL');
            $table->text('County');
            $table->integer('DaysOnMarket')->nullable();
            $table->string('Furnished',50)->nullable()->default('NULL');
            $table->char('InternetEntireListingDisplayYN',1)->nullable();
            $table->decimal('Latitude',14,8)->nullable();
            $table->bigInteger('ListAgentKeyNumeric')->nullable();
            $table->string('ListAgentMlsId',25)->nullable()->default('NULL');
            $table->string('ListingKeyNumeric',150)->nullable();
            $table->string('ListAOR',500)->nullable();
            $table->integer('ListPrice')->nullable();
            $table->integer('LivingArea')->nullable();
            $table->decimal('Longitude',14,8)->nullable();
            $table->datetime('ModificationTimestamp')->nullable();
            $table->string('NumberOfPets',50)->nullable()->default('NULL');
            $table->text('OwnerPays');
            $table->string('ParcelNumber',50)->nullable()->default('NULL');
            $table->text('ParcelNumberUnformatted');
            $table->text('ParkingFeatures');
            $table->text('PetsAllowed');
            $table->string('PetSize',50)->nullable()->default('NULL');
            $table->char('PoolPrivateYN',1)->nullable();
            $table->text('PrivateRemarks');
            $table->text('PropertyDescription');
            $table->string('PropertySubType',50)->nullable()->default('NULL');
            $table->text('SyndaPropType');
            $table->string('PropertyType',50)->nullable()->default('NULL');
            $table->string('StandardPropType')->nullable()->default('NULL');
            $table->string('TypeofProperty',250)->nullable();
            $table->string('CustomPropertyType',40)->nullable();
            $table->text('PublicRemarks');
            $table->text('PublicRemarksFiltered');
            $table->text('ShowingRequirements');
            $table->text('Amenities');
            $table->string('VowAutomatedValuationDisplay',10)->nullable()->default('NULL');
            $table->text('BuildingName');
            $table->string('SubdivisionName',50)->nullable()->default('NULL');
            $table->string('SubdivisionNum',10)->nullable()->default('NULL');
            $table->string('MoveInDollars',200)->nullable();
            $table->string('RentPeriod',50)->nullable();
            $table->string('MinimumLeasePeriod',50)->nullable();
            $table->string('RentIncludes',200)->nullable();
            $table->string('RentalDepositIncludes',250)->nullable();
            $table->string('IDXOptInYN',10)->nullable();
            $table->string('InternetYN',10)->nullable();
            $table->string('PetRestrictions',200)->nullable();
            $table->string('TaxYear',5)->nullable()->default('NULL');
            $table->string('AnyBrokerAdvertise',50)->default('No');
            $table->string('UnparsedAddress')->nullable()->default('NULL');
            $table->text('CustomAddressFull');
            $table->text('CustomAddress');
            $table->text('CustomAddress2');
            $table->text('CustomAddress3');
            $table->text('FullMailingAddress');
            $table->text('StandardAddress');
            $table->text('StandardAddressFull');
            $table->text('Utilities');
            $table->text('VirtualTourURLBranded');
            $table->char('WaterExtrasYN',1)->nullable();
            $table->integer('YearBuilt')->nullable();
            $table->datetime('PropertyInsertTime')->nullable();
            $table->datetime('PropertyLastUpdated')->nullable();
            $table->tinyInteger('UpdatedByAdmin')->default('-1');
            $table->datetime('AdminUpdatedTime')->nullable();
            $table->tinyInteger('ImageDownloaded')->default('0');
            $table->string('ListOfficeMlsId',250)->nullable();
            $table->string('AdvType',50)->default('ASA');
            $table->string('ListOfficeName',50)->nullable();
            $table->string('ListOfficePhone',50)->nullable();
            $table->string('ListAgentFullName')->nullable();
            $table->string('ListAgentFormattedName')->nullable()->default('NULL');
            $table->string('ListAgentDirectPhone',30)->nullable();
            $table->string('ListAgentUnformattedPhone',30)->nullable()->default('NULL');
            $table->string('ListAgentEmail')->nullable();
            $table->string('CoListAgentMlsId',50)->nullable();
            $table->string('CoListAgentFullName')->nullable();
            $table->string('CoListAgentDirectPhone',50)->nullable();
            $table->string('CoListAgentEmail',50)->nullable();
            /*$table->string('ListOfficeRESI_A_Count',20);
            $table->string('ListOfficeRLSE_A_Count',20);
            $table->string('ListOfficeRINC_A_Count',20);
            $table->string('ListOfficeLAND_A_Count',20);
            $table->string('ListOfficeBZOP_A_Count',20);
            $table->string('ListOfficeCOMM_A_Count',20);
            $table->string('ListOfficeCOML_A_Count',20);
            $table->string('RESI_A_Count',20);
            $table->string('RLSE_A_Count',20);
            $table->string('RINC_A_Count',20);
            $table->string('LAND_A_Count',20);
            $table->string('BZOP_A_Count',20);
            $table->string('COMM_A_Count',20);
            $table->string('COML_A_Count',20);*/
            $table->string('OfficeLeadType',50)->default('Co-Broke');
            $table->string('AgentLeadType',50)->default('Co-Broke');
            /*$table->integer('ListOfficeRESI_B_Count',10)->default('0');
            $table->integer('ListOfficeRLSE_B_Count',10)->default('0');
            $table->integer('ListOfficeRINC_B_Count',10)->default('0');
            $table->integer('ListOfficeLAND_B_Count',10)->default('0');
            $table->integer('ListOfficeBZOP_B_Count',10)->default('0');
            $table->integer('ListOfficeCOMM_B_Count',10)->default('0');
            $table->integer('ListOfficeCOML_B_Count',10)->default('0');
            $table->integer('RESI_B_Count',10)->default('0');
            $table->integer('RLSE_B_Count',10)->default('0');
            $table->integer('RINC_B_Count',10)->default('0');
            $table->integer('LAND_B_Count',10)->default('0');
            $table->integer('BZOP_B_Count',10)->default('0');
            $table->integer('COMM_B_Count',10)->default('0');
            $table->integer('COML_B_Count',10)->default('0');*/
            $table->tinyInteger('ImageUpdateNeeded')->default('1');
            $table->datetime('ImageDownloadedTime');
            $table->datetime('LastImageUpdated');
            $table->text('ImagesUrls');
            $table->tinyInteger('TobeRemoved')->default('0');
            $table->tinyInteger('GeocodeTried')->default('0');
            $table->integer('ImageTried')->default('0');
            $table->tinyInteger('DupRemoved')->default('0');
            $table->text('OK2AdvMLS');
            $table->text('GatedCommunityYN');
            $table->text('YearRoofInstalled');
            $table->text('ReasonForCancellation');
            $table->text('MaximumNumberOfPets');
            $table->text('TotalWeightLimit');
            $table->text('PetFeeDescription');
            $table->text('AssociationDepositYN');
            $table->text('AssociationDepositAmount');
            $table->text('CommissionDescription');
            $table->text('OwnerName');
            $table->text('LegalDescription');
            $table->text('ApnNumber');
            $table->text('OwnerPhone');
            $table->text('BuyerAgencyCompensation');
            $table->text('BuyerAgencyCompensationType');
            $table->text('TransactionBrokerCompensation');
            $table->text('TransactionBrokerCompensationType');
            $table->text('LeaseRenewalCompensation');
            $table->text('SubAgencyCompensation');
            $table->text('SubAgencyCompensationType');
            $table->text('AtomApiData');
            $table->text('Appliances');
            $table->text('ArchitecturalStyle');
            $table->text('AssociationAmenities');
            $table->text('AssociationFee');
            $table->text('AssociationFeeFrequency');
            $table->text('AssociationYN');
            $table->text('AttachedGarageYN');
            $table->text('AvailabilityDate');
            $table->text('AssociationFeeIncludes');
            $table->text('GarageSpaces');
            $table->text('CapRate');
            $table->text('NetOperatingIncome');
            $table->text('CarportSpaces');
            $table->text('ConstructionMaterials');
            $table->text('Cooling');
            $table->text('CoveredSpaces');
            $table->text('DirectionFaces');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
        Schema::dropIfExists('RetsPropertyDataPurged');
    }
}
