<?php

namespace App\Constants;

class PropertyConstants
{


    const LIMIT = 12;
    const HOME_PAGE_LIMIT = 4;
    const PAGE_DATA_LIMIT = 12;
    const MAP_PAGE_DATA_LIMIT = 500;
    const MAP_PAGE_DATA_LIMIT_SQL = 500;
    const AUTO_SUGGESTION_LIMIT = 5;
    const AUTO_SUGGESTION_DEFAULT_LIMIT = 5;
    const NEAREST_LIMIT = 12;
    const SIMILAR_LIST = 12;
    const PRICELIST = 150;
    const GTACITY = "Toronto";
    const YELP_API_KEY = "X3ASKQfAYvSj1IkY_wx307yfoxqfaTpDHxH0xqUlRcD_fkXwj73-K9wWzCHUDjVxMLAiC_ho0qoBy0AJVg7q0vJ3-6KMExTzPPFCMf3JJE0l0lmArUEXisGP7eDhX3Yx";
    const YELP_BUSINESS_SEARCH = "https://api.yelp.com/v3/businesses/search?term=";
    const RADIUS_FOR_NEARBY = '3000';
    const YELP_CLIENT_ID = "BXd8Ii2p6Y6bZdzhq4DGKQ";
    const FEATURED_CITY = "Markham";
    const FEATURED_PRICE = '1500000';
    const MAP_MARKERS_SELECT_DATA = [
        "ListingId",
        "id",
        "Latitude",
        "Longitude",
        "ListPrice",
        "Timestamp_sql",
        "ContractDate",
        "PropertyStatus",
        "Status"
    ];
    const SELECT_SOLD_DATA = [
        'id',
        "Orig_dol",
        'Sp_dol',
        'BedroomsTotal',
        'BathroomsFull',
        'Sqft',
        "ListPrice",
        "StandardAddress",
        "City",
        "ListingId",
        "Gar",
        "Dom",
        "ImageUrl",
        "PropertyStatus",
        "Status",
        "PropertySubType",
        'County',
        "PropertyType",
        "SlugUrl",
        "Park_spcs",
        "Community",
        "Extras",
        "Latitude",
        "Longitude",
        "Vow_exclusive",
        "Ad_text",
        "Timestamp_sql",
        "ContractDate"
    ];
    const SELECT_DATA = [
        'id',
        'BedroomsTotal',
        'BathroomsFull',
        'Sqft',
        "ListPrice",
        "StandardAddress",
        "City",
        "ListingId",
        "Gar",
        "Dom",
        "ImageUrl",
        "PropertyStatus",
        "Status",
        "Dom",
        "PropertySubType",
        "SlugUrl",
        "Community",
        "Latitude",
        "Longitude",
        "Vow_exclusive",
        "Timestamp_sql",
        "LastStatus",
        "ContractDate",
        "Sp_date"
        // "Extras",
        // "Orig_dol",
        // 'County',
        // "PropertyType",
        // "Park_spcs",
        // "Ad_text",
    ];
    const HOME_SELECT_DATA = [
        'id',
        "Orig_dol",
        'BedroomsTotal',
        'BathroomsFull',
        'Sqft',
        "ListPrice",
        "StandardAddress",
        "ListingId",
        "Gar",
        "Dom",
        "ImageUrl",
        "PropertyStatus",
        "Dom",
        "SlugUrl",
        "Park_spcs",
        "Vow_exclusive",
        "Ad_text",
        "City"
    ];
    const STATS_PROPERTY_DETAILS_DATA = [
        "id",
        "Extras",
        "ListPrice",
        "ListingId",
        "ImageUrl",
        "SlugUrl",

    ];
    const PROPERTY_DETAILS_SELECT_DATA = [
        'id',
        'Br',
        'Bath_tot',
        "Orig_dol",
        'Sqft',
        "Lp_dol",
        "Addr",
        "Area",
        "Ml_num",
        "Gar_spaces",
        "Dom",
        "Kit_plus",
        "S_r",
        "Type_own1_out",
        'County',
        "Water",
        "Taxes",
        "Extras",
        "Ad_text",
        "Rltr",
        "Status",
        "Community",
        "A_c",
        "Bsmt1_out",
        "Fpl_num",
        "Cross_st",
        "Gar_type",
        "Fuel",
        "Pool",
        "Latitude",
        "Longitude",
        "RoomsDescription",
        "SlugUrl",
        "Park_spcs",
        "Prop_feat1_out",
        "Prop_feat2_out",
        "Timestamp_sql",
        "property_insert_time",
        "property_last_updated",
        "Tour_url",
        "Style",
        "Yr_built",
        "Municipality",
        "Rms",
        "Sewer",
        "Lotsz_code",
        "Depth",
        "Heating",
        "Heat_inc",
        "Water_inc",
        "Prkg_inc",
        "Water",
        "Fuel",
        "Tot_park_spcs",
        "Cable",

        "Comp_pts",
        "Front_ft",
        "Constr1_out",
        "Constr2_out",
        "Yr",
        "Comel_inc",
        "Cac_inc",
        "Den_fr",
        "Sp_dol",
        "Lsc",
        "Timestamp_sql",
        "Ld",
        "Cd",
        "StandardAddress",
        "Dt_sus",
        "Dt_ter"
        // "Bldg_amen1_out",
        // "Bldg_amen1_out",
        // "Pets",
        // "Park_fac",
        // "Maint",
        // "Condo_corp",
        // "Corp_num",
        // "Cond_txinc",
        // "Insur_bldg",
    ];
    const PROPERTY_DETAILS_SELECT_DATA_COMM = [
        'id',
        'Bath_tot',
        "Orig_dol",
        "Lp_dol",
        "Addr",
        "Area",
        "Ml_num",
        "Dom",
        "S_r",
        "Type_own1_out",
        'County',
        "Water",
        "Taxes",
        "Extras",
        "Ad_text",
        "Rltr",
        "Status",
        "Community",
        "A_c",
        "Bsmt1_out",
        "Cross_st",
        "Gar_type",
        "Latitude",
        "Longitude",
        "SlugUrl",
        "Park_spcs",
        "Timestamp_sql",
        "property_insert_time",
        "property_last_updated",
        "Tour_url",
        "Yr_built",
        "Municipality",
        "Sewer",
        "Lotsz_code",
        "Depth",
        "Heating",
        "Water",
        "Front_ft",
        "Maint",
        "Sp_dol",
        "Yr",
        // "Style",
        // "Rms",
        // "Heat_inc",
        // "Water_inc",
        // "Prkg_inc",
        // "Fuel",
        // "Tot_park_spcs",
        // "Cable",

        // "Comp_pts",
        // "Condo_corp",
        // "Corp_num",
        // "Constr1_out",
        // "Constr2_out",
        // "Bldg_amen1_out",
        // "Bldg_amen1_out",
        // "Pets",
        // "Park_fac",
        // "Cond_txinc",
        // "Insur_bldg",
        // "Comel_inc",
        // "Cac_inc",
        // "Den_fr",
    ];
    const PROPERTY_DETAILS_SELECT_DATA_CONDO = [
        'id',
        'Br',
        'Bath_tot',
        "Orig_dol",
        'Sqft',
        "Lp_dol",
        "Addr",
        "Area",
        "Ml_num",
        "Dom",
        "Kit_plus",
        "S_r",
        "Type_own1_out",
        'County',
        "Taxes",
        "Extras",
        "Ad_text",
        "Rltr",
        "Status",
        "Community",
        "A_c",
        "Bsmt1_out",
        "Fpl_num",
        "Cross_st",
        "Gar_type",
        "Fuel",
        "Latitude",
        "Longitude",
        "RoomsDescription",
        "SlugUrl",
        "Park_spcs",
        "Prop_feat1_out",
        "Prop_feat2_out",
        "Timestamp_sql",
        "property_insert_time",
        "property_last_updated",
        "Tour_url",
        "Style",
        "Yr_built",
        "Municipality",
        "Rms",
        "Heating",
        "Heat_inc",
        "Water_inc",
        "Prkg_inc",
        "Fuel",
        "Tot_park_spcs",
        "Cable",
        "Condo_corp",
        "Corp_num",
        "Constr1_out",
        "Constr2_out",
        "Bldg_amen1_out",
        "Bldg_amen2_out",
        "Pets",
        "Park_fac",
        "Maint",
        "Yr",
        "Cond_txinc",
        "Insur_bldg",
        "Comel_inc",
        "Cac_inc",
        "Den_fr",
        "Sp_dol",
        "Lsc",
        "Ld",
        "Cd",
        "StandardAddress",
        "Dt_sus",
        "Dt_ter"
    ];
    const MAP_SELECT_DATA = [
        'id',
        "ImageUrl",
        "Orig_dol",
        "SlugUrl",
        "PropertyStatus",
        "ListPrice",
        "StandardAddress",
        'BedroomsTotal',
        'BathroomsFull',
        'Sqft',
        "Dom",
        "ListingId",
        "Latitude",
        "Longitude",
        "ShortPrice",
        "Status",
        "ContractDate"

    ];
    const PROPERTY_STATS_DATA = [
        'id',
        "ListPrice",
        "StandardAddress",
        "City",
        "ListingId",
        "ImageUrl",
        "MlsStatus",
        "SlugUrl",
    ];
}
