<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateRetsPropertyDataResisTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('rets_property_data_resi', function (Blueprint $table) {
            $table->id();
            $table->string('Comp_pts', 50)->nullable();
            $table->string('Cond', 24)->nullable();
            $table->string('Constr1_out', 50)->nullable();
            $table->string('Constr2_out', 50)->nullable();
            $table->string('County', 16)->nullable();
            $table->string('Cross_st', 30)->nullable();
            $table->string('Den_fr', 50)->nullable();
            $table->decimal('Depth');
            $table->string('Disp_addr', 1)->nullable();
            $table->decimal('Dom');
            $table->string('Drive', 50)->nullable();
            $table->date('Dt_sus')->nullable();
            $table->date('Dt_ter')->nullable();
            $table->string('Elec', 50)->nullable();
            $table->string('Elevator', 50)->nullable();
            $table->string('Extras', 240)->nullable();
            $table->string('Farm_agri', 50)->nullable();
            $table->string('Fpl_num', 50)->nullable();
            $table->decimal('Front_ft');
            $table->string('Fuel', 50)->nullable();
            $table->string('Furnished', 50)->nullable();
            $table->decimal('Gar_spaces');
            $table->string('Gar_type', 50)->nullable();
            $table->string('Gas', 50)->nullable();
            $table->string('Heat_inc', 50)->nullable();
            $table->string('Heating', 50)->nullable();
            $table->string('Hydro_inc', 50)->nullable();
            $table->date('Input_date')->nullable();
            $table->string('Internet', 50)->nullable();
            $table->decimal('Orig_dol');
            $table->string('Oth_struc1_out', 50)->nullable();
            $table->string('Oth_struc2_out', 50)->nullable();
            $table->string('Outof_area', 16)->nullable();
            $table->string('Parcel_id', 9)->nullable();
            $table->decimal('Park_chgs');
            $table->decimal('Park_spcs');
            $table->string('Pay_freq', 50)->nullable();
            $table->decimal('Perc_dif');
            $table->string('Pool', 50)->nullable();
            $table->string('Pr_lsc', 50)->nullable();
            $table->string('Prkg_inc', 50)->nullable();
            $table->string('Prop_feat1_out', 50)->nullable();
            $table->string('Prop_feat2_out', 50)->nullable();
            $table->string('Prop_feat3_out', 50)->nullable();
            $table->string('Prop_feat4_out', 50)->nullable();
            $table->string('Prop_feat5_out', 50)->nullable();
            $table->string('Prop_feat6_out', 50)->nullable();
            $table->decimal('Rm3_len');
            $table->string('Rm3_out', 50)->nullable();
            $table->decimal('Rm3_wth');
            $table->string('Rm4_dc1_out', 50)->nullable();
            $table->string('Rm4_dc2_out', 50)->nullable();
            $table->string('Rm4_dc3_out', 50)->nullable();
            $table->decimal('Rm4_len');
            $table->string('Rm4_out', 50)->nullable();
            $table->decimal('Rm4_wth');
            $table->string('Rm5_dc1_out', 50)->nullable();
            $table->string('Rm5_dc2_out', 50)->nullable();
            $table->string('Rm5_dc3_out', 50)->nullable();
            $table->decimal('Rm5_len');
            $table->string('Rm5_out', 50)->nullable();
            $table->decimal('Rm5_wth');
            $table->string('Rm6_dc1_out', 50)->nullable();
            $table->string('Rm6_dc2_out', 50)->nullable();
            $table->string('Rm6_dc3_out', 50)->nullable();
            $table->decimal('Rm6_len');
            $table->string('Rm6_out', 50)->nullable();
            $table->decimal('Rm6_wth');
            $table->string('Rm7_dc1_out', 50)->nullable();
            $table->string('Rm7_dc2_out', 50)->nullable();
            $table->string('Rm7_dc3_out', 50)->nullable();
            $table->decimal('Rm7_len');
            $table->string('Rm7_out', 50)->nullable();
            $table->decimal('Rm7_wth');
            $table->string('Rm8_dc1_out', 50)->nullable();
            $table->string('Rm8_dc2_out', 50)->nullable();
            $table->string('Rm8_dc3_out', 50)->nullable();
            $table->decimal('Rm8_len');
            $table->string('Rm8_out', 50)->nullable();
            $table->decimal('Rm8_wth');
            $table->string('Rm9_dc1_out', 50)->nullable();
            $table->string('Rm9_dc2_out', 50)->nullable();
            $table->string('Rm9_dc3_out', 50)->nullable();
            $table->decimal('Rm9_len');
            $table->string('Rm9_out', 50)->nullable();
            $table->decimal('Rm9_wth');
            $table->decimal('Rms');
            $table->decimal('Rooms_plus');
            $table->string('Uffi', 50)->nullable();
            $table->date('Unavail_dt')->nullable();
            $table->string('Util_cable', 50)->nullable();
            $table->string('Util_tel', 50)->nullable();
            $table->string('Vend_pis', 50)->nullable();
            $table->date('Vtour_updt')->nullable();
            $table->string('Water', 50)->nullable();
            $table->string('Water_inc', 50)->nullable();
            $table->string('Waterfront', 50)->nullable();
            $table->decimal('Wcloset_p1');
            $table->decimal('Wcloset_p2');
            $table->decimal('Wcloset_p3');
            $table->decimal('Wcloset_p4');
            $table->decimal('Wcloset_p5');
            $table->decimal('Wcloset_t1');
            $table->string('Wcloset_t1lvl', 50)->nullable();
            $table->decimal('Wcloset_t2');
            $table->string('Wcloset_t2lvl', 50)->nullable();
            $table->decimal('Wcloset_t3');
            $table->string('Wcloset_t3lvl', 50)->nullable();
            $table->decimal('Wcloset_t4');
            $table->string('Wcloset_t4lvl', 50)->nullable();
            $table->decimal('Wcloset_t5');
            $table->string('Wcloset_t5lvl', 50)->nullable();
            $table->string('Wtr_suptyp', 50)->nullable();
            $table->date('Xd')->nullable();
            $table->date('Xdtd')->nullable();
            $table->decimal('Yr');
            $table->string('Yr_built', 50)->nullable();
            $table->string('Zip', 7)->nullable();
            $table->string('Zoning', 40)->nullable();
            $table->date('Timestamp_sql')->nullable();
            $table->string('Municipality_code', 50)->nullable();
            $table->string('Area', 40)->nullable();
            $table->string('Community', 44)->nullable();
            $table->string('Cert_lvl', 25)->nullable();
            $table->string('Energy_cert', 50)->nullable();
            $table->string('Handi_equipped', 50)->nullable();
            $table->string('Oh_to1', 8)->nullable();
            $table->string('Oh_to2', 8)->nullable();
            $table->string('Oh_to3', 8)->nullable();
            $table->string('Oh_from1', 8)->nullable();
            $table->string('Oh_from2', 8)->nullable();
            $table->string('Oh_from3', 8)->nullable();
            $table->string('A_c', 50)->nullable();
            $table->string('Acres', 50)->nullable();
            $table->text('Ad_text');
            $table->decimal('Addl_mo_fee');
            $table->string('Addr', 35)->nullable();
            $table->string('All_inc', 50)->nullable();
            $table->string('Apt_num', 7)->nullable();
            $table->decimal('Ass_year');
            $table->decimal('Bath_tot');
            $table->decimal('Br');
            $table->decimal('Br_plus');
            $table->string('Bsmt1_out', 50)->nullable();
            $table->string('Bsmt2_out', 50)->nullable();
            $table->string('Cable', 50)->nullable();
            $table->string('Cac_inc', 50)->nullable();
            $table->date('Cd')->nullable();
            $table->string('Central_vac', 50)->nullable();
            $table->date('Cndsold_xd')->nullable();
            $table->string('Com_coopb', 40)->nullable();
            $table->string('Comel_inc', 50)->nullable();
            $table->string('Irreg', 40)->nullable();
            $table->decimal('Kit_plus');
            $table->string('Laundry', 50)->nullable();
            $table->string('Laundry_lev', 50)->nullable();
            $table->date('Ld')->nullable();
            $table->string('Lease', 50)->nullable();
            $table->string('Lease_term', 50)->nullable();
            $table->string('Legal_desc', 50)->nullable();
            $table->string('Level1', 50)->nullable();
            $table->string('Level10', 50)->nullable();
            $table->string('Level11', 50)->nullable();
            $table->string('Level12', 50)->nullable();
            $table->string('Level2', 50)->nullable();
            $table->string('Level3', 50)->nullable();
            $table->string('Level4', 50)->nullable();
            $table->string('Level5', 50)->nullable();
            $table->string('Level6', 50)->nullable();
            $table->string('Level7', 50)->nullable();
            $table->string('Level8', 50)->nullable();
            $table->string('Level9', 50)->nullable();
            $table->string('Lot_fr_inc', 1)->nullable();
            $table->string('Lotsz_code', 50)->nullable();
            $table->decimal('Lp_dol');
            $table->string('Lsc', 50)->nullable();
            $table->string('Lse_terms', 12)->nullable();
            $table->string('Ml_num', 8)->nullable();
            $table->decimal('Mmap_col');
            $table->decimal('Mmap_page');
            $table->string('Mmap_row', 1)->nullable();
            $table->decimal('Num_kit');
            $table->string('Occ', 14)->nullable();
            $table->string('Prop_mgmt', 60)->nullable();
            $table->string('Pvt_ent', 50)->nullable();
            $table->string('Retirement', 50)->nullable();
            $table->text('Rltr');
            $table->string('Rm1_dc1_out', 50)->nullable();
            $table->string('Rm1_dc2_out', 50)->nullable();
            $table->string('Rm1_dc3_out', 50)->nullable();
            $table->decimal('Rm1_len');
            $table->string('Rm1_out', 50)->nullable();
            $table->decimal('Rm1_wth');
            $table->string('Rm10_dc1_out', 50)->nullable();
            $table->string('Rm10_dc2_out', 50)->nullable();
            $table->string('Rm10_dc3_out', 50)->nullable();
            $table->decimal('Rm10_len');
            $table->string('Rm10_out', 50)->nullable();
            $table->decimal('Rm10_wth');
            $table->string('Rm11_dc1_out', 50)->nullable();
            $table->string('Rm11_dc2_out', 50)->nullable();
            $table->string('Rm11_dc3_out', 50)->nullable();
            $table->decimal('Rm11_len');
            $table->string('Rm11_out', 50)->nullable();
            $table->decimal('Rm11_wth');
            $table->string('Rm12_dc1_out', 50)->nullable();
            $table->string('Rm12_dc2_out', 50)->nullable();
            $table->string('Rm12_dc3_out', 50)->nullable();
            $table->decimal('Rm12_len');
            $table->string('Rm12_out', 50)->nullable();
            $table->decimal('Rm12_wth');
            $table->string('Rm2_dc1_out', 50)->nullable();
            $table->string('Rm2_dc2_out', 50)->nullable();
            $table->string('Rm2_dc3_out', 50)->nullable();
            $table->decimal('Rm2_len');
            $table->string('Rm2_out', 50)->nullable();
            $table->decimal('Rm2_wth');
            $table->string('Rm3_dc1_out', 50)->nullable();
            $table->string('Rm3_dc2_out', 50)->nullable();
            $table->string('Rm3_dc3_out', 50)->nullable();
            $table->string('S_r', 50)->nullable();
            $table->string('Sewer', 50)->nullable();
            $table->decimal('Sp_dol');
            $table->string('Spec_des1_out', 50)->nullable();
            $table->string('Spec_des2_out', 50)->nullable();
            $table->string('Spec_des3_out', 50)->nullable();
            $table->string('Spec_des4_out', 50)->nullable();
            $table->string('Spec_des5_out', 50)->nullable();
            $table->string('Spec_des6_out', 50)->nullable();
            $table->string('Sqft', 50)->nullable();
            $table->string('St', 20)->nullable();
            $table->string('St_dir', 50)->nullable();
            $table->string('St_num', 7)->nullable();
            $table->string('St_sfx', 50)->nullable();
            $table->string('Status', 50)->nullable();
            $table->string('Style', 50)->nullable();
            $table->decimal('Taxes');
            $table->date('Td')->nullable();
            $table->string('Tour_url', 100)->nullable();
            $table->string('Community_code', 50)->nullable();
            $table->string('Area_code', 50)->nullable();
            $table->decimal('Tv');
            $table->text('Type_own_srch');
            $table->string('Type_own1_out', 50)->nullable();
            $table->string('Municipality_district', 44)->nullable();
            $table->string('Municipality', 40)->nullable();
            $table->date('Pix_updt')->nullable();
            $table->date('Oh_date1')->nullable();
            $table->date('Oh_date2')->nullable();
            $table->date('Oh_date3')->nullable();
            $table->date('Oh_dt_stamp')->nullable();
            $table->string('Green_pis', 50)->nullable();
            $table->date('Poss_date')->nullable();
            $table->string('Water_body', 50)->nullable();
            $table->string('Water_type', 50)->nullable();
            $table->text('Oh_Link1');
            $table->text('Oh_Link2');
            $table->text('Oh_Link3');
            $table->string('Oh_Type1', 50)->nullable();
            $table->string('Oh_Type2', 50)->nullable();
            $table->string('Oh_Type3', 50)->nullable();
            $table->decimal('Water_front');
            $table->string('Access_prop1', 50)->nullable();
            $table->string('Access_prop2', 50)->nullable();
            $table->string('Water_feat1', 50)->nullable();
            $table->string('Water_feat2', 50)->nullable();
            $table->string('Water_feat3', 50)->nullable();
            $table->string('Water_feat4', 50)->nullable();
            $table->string('Water_feat5', 50)->nullable();
            $table->string('Shoreline1', 50)->nullable();
            $table->string('Shoreline2', 50)->nullable();
            $table->string('Shore_allow', 50)->nullable();
            $table->string('Shoreline_exp', 50)->nullable();
            $table->string('Alt_power1', 50)->nullable();
            $table->string('Alt_power2', 50)->nullable();
            $table->string('Easement_rest1', 50)->nullable();
            $table->string('Easement_rest2', 50)->nullable();
            $table->string('Easement_rest3', 50)->nullable();
            $table->string('Easement_rest4', 50)->nullable();
            $table->string('Rural_svc1', 50)->nullable();
            $table->string('Rural_svc2', 50)->nullable();
            $table->string('Rural_svc3', 50)->nullable();
            $table->string('Rural_svc4', 50)->nullable();
            $table->string('Rural_svc5', 50)->nullable();
            $table->string('Water_acc_bldg1', 50)->nullable();
            $table->string('Water_acc_bldg2', 50)->nullable();
            $table->string('Water_del_feat1', 50)->nullable();
            $table->string('Water_del_feat2', 50)->nullable();
            $table->string('Sewage1', 50)->nullable();
            $table->string('Sewage2', 50)->nullable();
            $table->string('Potl', 50)->nullable();
            $table->decimal('Tot_park_spcs');
            $table->string('Link_yn', 50)->nullable();
            $table->string('Link_Comment', 50)->nullable();
            $table->date('Oh_date4')->nullable();
            $table->date('Oh_date5')->nullable();
            $table->date('Oh_date6')->nullable();
            $table->string('Oh_from4', 8)->nullable();
            $table->string('Oh_from5', 8)->nullable();
            $table->string('Oh_from6', 8)->nullable();
            $table->text('Oh_Link4');
            $table->text('Oh_Link5');
            $table->text('Oh_Link6');
            $table->string('Oh_to4', 8)->nullable();
            $table->string('Oh_to5', 8)->nullable();
            $table->string('Oh_to6', 8)->nullable();
            $table->string('Oh_Type4', 50)->nullable();
            $table->string('Oh_Type5', 50)->nullable();
            $table->string('Oh_Type6', 50)->nullable();
            $table->tinyInteger('processed')->nullable();
            $table->datetime('property_insert_time')->nullable();
            $table->datetime('property_last_updated')->nullable();
            $table->tinyInteger('image_downloaded')->nullable();
            $table->integer('image_download_tried')->nullable();
            $table->datetime('image_downloaded_time')->nullable();
            $table->integer('mls_no')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('rets_property_data_resi');
    }
}
